### ISSUE TITLE
Make Runtimes Generic

### ISSUE THREAD

**Issue by paulgb** [jamsocket/plane#712]
- [x] Make the executor configuration generic (#713)
- [x] Turn executor config into an enum (#717)
- [x] Make the executor itself generic
  - [x] Move pruning loop into `PlaneDocker` (#718)
  - [x] Move readiness check into `PlaneDocker` (#728)
  - [x] Move Docker construction into `PlaneDocker` (#719)
  - [x] Rename `PlaneDocker` to `DockerRuntime` (#720)
  - [x] Make `ContainerId` an implementation detail of `DockerRuntime` (#721)
  - [x] Generalize pull (#722)
  - [x] Implement `Runtime` trait (#723)
  - [x] Move metrics loop into docker side (#724)
  - [x] Replace `DockerRuntime` with generic `Runtime` in the main loop
    - [x] Make `BackendManager` generic over runtime (#727)
  - [x] Refactor codebase to create a module for runtimes
- [x] Send backend ID as an HTTP header to the backend (so that multiple backends can share a port) (#714)
- [x] Spec out a Drone <> Executor wire protocol (#766)
- [x] Implement an executor that uses the wire protocol over domain sockets (#766, #780)
- [ ] Create a mock executor and use it to add integration tests
